/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IMart, IMartInterface } from "../IMart";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "string",
        name: "_uri",
        type: "string",
      },
    ],
    name: "safeMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_marketplace",
        type: "address",
      },
    ],
    name: "setMarketplace",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMart__factory {
  static readonly abi = _abi;
  static createInterface(): IMartInterface {
    return new utils.Interface(_abi) as IMartInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IMart {
    return new Contract(address, _abi, signerOrProvider) as IMart;
  }
}
